### ISSUE TITLE
Processor interface pixel format change?

### ISSUE THREAD

**Issue by mik3y** [garthwebb/dance-floor#39]
Currently processors return pixels as a 3-tuple of `(red, green, blue)`, which are integers on `[0, self.max_value]`. `self.max_value` is a dynamic value within a processor, which can vary based on (a) the dynamic range of the show's driver, and (b) the current brightness called for by the controller.

I was thinking both (a) and (b) are leaky abstractions of sorts, since they're controller concepts that a "generic" processor shouldn't have to worry about. We could simplify processor code by moving these back to an unchanging absolute range, like `[0-255]` for 8-bit color.

As an unrelated thought, I also thought in the future it might be really interesting to support a mode where you can "stack" or layer processors, similar to e.g. layers in photoshop, where an alpha channel describes how much of the next layer beneath to blend.

Both of these combined: What do you think about changing the "pixel" return value to something like an absolute `(red, greed, blue, alpha)`; and consequently, move scaling currently accomplished by `max_value` into the `Controller`?

**Comment by mik3y** [comment]
not sure if you get notifications on issue create, so just in case: yo @garthwebb !

**Comment by mik3y** [comment]
Oh, a slight tweak on this idea, we could support _either_ 4-tuple `(r, g, b, a)` pixels, or 3-tuple `(r, g, b)` with implied alpha of 100% (for processors that don't care about alpha). In either case, r/g/b/a would all be on a standard range as in the other part of the proposal, like `[0.0, 1.0]` or `[0, 255]`.

**Comment by garthwebb** [comment]
So the driver class _should_ be the thing that dictates what the max value is, and in fact it is, but it's plumbed through in a weird way right now.  Having the `max_value` field set and defined within the `Base` processor class is meant to make it so the 'processor shouldn't have to worry about' it.

I think the Base.__init__ should take a controller object and then `Base.max_value()` asks the controller what the max value is (rather than Controller pushing the value out to the processor as current).  The `Controller` should get its value from the `Driver` and modify it depending on the input it gets about dimming the floor.

I don't want to limit us to 8-bit color channels because it just can't do good fades since you get at best 256 steps if starting from full on.  Even then, the human eye is much more perceptive to lower luminosity levels, so it works out to ~128 steps (the top 128 you don't really notice).

I know we could get that back with the alpha channel, but that would only come into play for Processors that want to intentionally dim.  For processors that are varying in color over time the effect will be noticeable chunkiness at lower light levels.

If we really wanted to have a constant value for Processors, I'd advocate for 0.0 to 1.0 and then do the math to scale up in the driver.  However, I'd worry if the little RaspberryPi could handle 196 additional floating point calculations per frame.  Already with the Ripple pattern requesting 120 fps (it does look better) when running on the RaspPi it can't finish a frame in time.  As a side note, I think it would be good to make a performance pass at some point.

Finally, another angle to take if we start messing with pixel representation is to go to HSV.  We need RGB simply because it's the physical representation of the lighting, but its garbage to work with in Processors.  Almost always, you just want a color and you want to vary that color in a sane way.  Mixing R, G, B is not sane.

**Comment by mik3y** [comment]
Ah, great points!

> If we really wanted to have a constant value for Processors, I'd advocate for 0.0 to 1.0 and then do the math to scale up in the driver. However, I'd worry if the little RaspberryPi could handle 196 additional floating point calculations per frame. Already with the Ripple pattern requesting 120 fps (it does look better) when running on the RaspPi it can't finish a frame in time. As a side note, I think it would be good to make a performance pass at some point.

My thoughts as well! One of the things I've wanted to do for a while is benchmark some of the existing processors, especially before making changes that could affect (or are suspected to improve) performance. Some of my recent changes to inject the clock now make this a lot easier (since we can call `get_next_frame` as fast as we want, with a fake clock)... lemme pause on the pixel idea here, write the benchmarker, and then see where we end up.

(ninja edit: simple benchmarker in #43)

**Comment by mik3y** [comment]
implemented in #46 - closing!
